schema_version = "1.0.0"

id = "a3da_parser"
name = "A3DA Parser"
version = "1.0.1"
blender_version_min = "5.0.0"

tagline = "Import & export Project Diva A3DA animation files"
maintainer = "Hans Xwh"
type = "add-on"
tags = ["Import-Export"]
license = ["SPDX:GPL-3.0-or-later"]
copyright = ["2026 Hans_Xwh"]

website = "https://github.com/Hans-xwh/A3DA-Parser"

[permissions]
files = "Import and export Project Diva A3DA animation files"

[build]
paths_exclude_pattern = [
    "__pycache__/",
    "changelog.md",
    "*.old"
]